PipelineSecrets: {}
mqttserver:
  env:
    MqttJobProcessor_FeatureToggling__CoraAlertCreatedEventHandler: true
    MqttJobProcessor_FeatureToggling__UserCreationRequestedEventHandler: true
    MqttJobProcessor_FeatureToggling__UserCreationConfirmedEventHandler: true
    MqttJobProcessor_FeatureToggling__UserCreationRejectedEventHandler: true
priluxwebui:
  env:
    App__CorsOrigins: https://prilux-vial-ui.jx-staging.dativepartners.eu,https://*.dativepartners.eu,http://*.dativepartners.eu,http://localhost:4200,http://localhost:8080,http://localhost:8081,http://localhost:3000,https://priluxwebuiv2.dev-staging.dativepartners.eu,https://priluxwebui.dev-staging.dativepartners.eu,https://.dativepartners.eu,https://nix.dative.app
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: dativepartners.eu
    exposer: Ingress
    http: "true"
jenkins:
  Servers:
    Global:
      EnvVars:
        TILLER_NAMESPACE: kube-system
prow: {}
